- hosts: all
  become: true
  tasks:

  - name: install python3
    apt:
      name: python3

  - name: install pip3
    apt:
      name: python3-pip

  - name: default pip3
    apt:
       update-alternatives --install /usr/bin/python 3 python3 /usr/bin/python3.1
